[build]
builder = "nixpacks"
buildCommand = "apt-get update && apt-get install -y ffmpeg && npm ci"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "true"
PUPPETEER_SKIP_DOWNLOAD = "true"
RAILWAY_FFMPEG_SIMPLE = "true" 