[build]
builder = "nixpacks"
buildCommand = "npm ci && chmod +x node_modules/ffmpeg-static/ffmpeg"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "true"
PUPPETEER_SKIP_DOWNLOAD = "true" 